import React, { useState } from 'react';
import { AlertTriangle, Info, X } from 'lucide-react';

interface DisclaimerBannerProps {
  compact?: boolean;
}

export const DisclaimerBanner: React.FC<DisclaimerBannerProps> = ({ compact = false }) => {
  const [isExpanded, setIsExpanded] = useState(false);

  return (
    <aside
      id="academic-disclaimer-banner"
      role="region"
      aria-label="Academic Demo Disclaimer"
      className="w-full bg-amber-50 dark:bg-amber-950/40 border-2 border-amber-400 dark:border-amber-600/60 rounded-xl p-4 md:p-4.5 shadow-sm text-amber-900 dark:text-amber-100 transition-all duration-200"
    >
      <div className="flex items-start gap-3.5">
        <div className="p-2 bg-amber-500/15 dark:bg-amber-500/25 rounded-lg shrink-0 text-amber-700 dark:text-amber-300">
          <AlertTriangle className="w-5 h-5" aria-hidden="true" />
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center justify-between gap-2">
            <h2 className="font-semibold text-base flex items-center gap-2 text-amber-950 dark:text-amber-200">
              <span>Academic Demo & Educational Research Purposes Only</span>
              <span className="text-xs uppercase tracking-wider font-bold px-2 py-0.5 rounded-full bg-amber-200 dark:bg-amber-900/80 text-amber-800 dark:text-amber-200 border border-amber-300 dark:border-amber-700">
                Not Medical Advice
              </span>
            </h2>
          </div>
          <p className="mt-1 text-sm text-amber-900/90 dark:text-amber-200/90 leading-relaxed">
            This application is created strictly as an academic prototype to demonstrate structured AI reasoning (5-point clinical guidance). It is <strong>NOT</strong> a certified medical diagnostic tool, clinical triage system, or prescription provider.
          </p>
          
          {isExpanded && (
            <div className="mt-3 pt-3 border-t border-amber-300/60 dark:border-amber-700/60 text-xs text-amber-900/80 dark:text-amber-200/80 space-y-1.5 leading-normal animate-fadeIn">
              <p>
                • <strong>Emergency Situations:</strong> If you or someone around you is experiencing severe trauma, chest pain, uncontrolled bleeding, respiratory distress, or sudden numbness, call your local emergency services (e.g., 911, 112, 999) immediately.
              </p>
              <p>
                • <strong>Clinical Evaluation:</strong> Do not delay, disregard, or alter prescribed medical therapy based on any output generated by this demonstration system.
              </p>
            </div>
          )}

          <div className="mt-2 flex items-center gap-4">
            <button
              id="btn-toggle-disclaimer-details"
              type="button"
              onClick={() => setIsExpanded(!isExpanded)}
              className="text-xs font-medium text-amber-800 dark:text-amber-300 hover:underline flex items-center gap-1 cursor-pointer focus:outline-none focus:ring-2 focus:ring-amber-500 rounded"
            >
              <Info className="w-3.5 h-3.5" />
              <span>{isExpanded ? 'Hide full academic notice' : 'Read full safety protocol & notice'}</span>
            </button>
          </div>
        </div>
      </div>
    </aside>
  );
};
